"""notes belong to projects

Revision ID: 61f758970259
Revises: 89e10d0af509
Create Date: 2026-07-13 18:24:04.244681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f758970259'
down_revision: Union[str, Sequence[str], None] = '89e10d0af509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('project_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('notes_document_id_fkey'), 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'projects', ['project_id'], ['id'])
    op.drop_column('notes', 'document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key(op.f('notes_document_id_fkey'), 'notes', 'documents', ['document_id'], ['id'])
    op.drop_column('notes', 'project_id')
    # ### end Alembic commands ###
